"""
Decompiled / Reconstructed Module: services.tabs.clone_video.youtube_clone_service
Source PyC: youtube_clone_service.pyc

Docstring:
YouTube Clone Service - SIMPLIFIED VERSION
Analyze source videos and generate clone/remix scripts.

Core flow:
   - one prompt assembly path
   - fixed-duration scene count from clip_duration_seconds
   - dynamic output examples generated by _build_clone_output_example()
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple, Union, Callable

# --- Module Constants & Globals ---
Dict = typing.Dict
Mapping = typing.Mapping
Optional = typing.Optional
Callable = typing.Callable
Tuple = typing.Tuple
Union = typing.Union
List = typing.List
log = <utils.module_logger.ModuleLogger object at 0x00000264E64A1040>
_MAX_INLINE_VIDEO_BYTES = 20000000
_TIKTOK_RESOLVER_MAX_BYTES = 1073741824
_TIKTOK_AUDIO_ONLY_EXTENSIONS = {'.opus', '.oga', '.ogg', '.mp3', '.flac', '.m4a', '.wma', '.aac', '.wav'}
_TIKTOK_MEDIA_HOSTS = {'tiktokv.com', 'tikwm.com', 'tikcdn.io', 'tiktokcdn-us.com', 'byteicdn.com', 'muscdn.com', 'tiktokcdn.com', 'tikmate.app', 'byteoversea.com'}
FORMAT_RULES = '⚠️ CRITICAL REQUIREMENTS:\n\n0. **Top-level JSON keys REQUIRED:** `content_profile`, `entity_library`, `anchor_plan`, `block_plan`, `scenes`.\n   - `entity_library` is the primary semantic model and ... [truncated]
CONTENT_ANALYSIS = '## CONTENT ANALYSIS (Watch + Listen to ENTIRE video first)\n\n**STEP 1: WATCH & LISTEN — Classify the video:**\n- VIDEO TYPE: narrative_dialogue | narrative_action_silent | documentary_narration | in... [truncated]
VISUAL_TEXT_OMISSION_RULES = '## OCR / ON-SCREEN TEXT OMISSION RULES\n\nVision may read visible written text in the source video correctly. Use that only as OCR-only context to understand the scene, timing, topic, or intent.\n\nW... [truncated]
ENTITY_LIBRARY_SPECS = '## ENTITY LIBRARY CONTRACT (PRIMARY)\n\nReturn `entity_library` only.\n- `entity_library` is the source of truth: everything that may need lock/reference/routing.\n\nRequired entity_library groups:\n... [truncated]
FAMOUS_CHARACTER_REWRITE_RULES = "## FAMOUS / PROTECTED CHARACTER IDENTITY (CLASSIFY, THEN REWRITE)\n\nThe source video may contain a well-known franchise character, copyrighted fictional\ncharacter, celebrity portrayal, mascot, or o... [truncated]
SCENE_WRITING = '## SCENE DESCRIPTION GUIDELINES (AUTO MODE - {clip_duration_seconds}s scenes)\n\n**Structure (3 parts per scene):**\n1. **Beginning:** What starts happening\n2. **Middle:** Action develops\n3. **End:... [truncated]
CREATIVE_VIDEO_ANALYSIS_OVERRIDE = "\n⚠️ CREATIVE MODE ACTIVE — You are NOT copying this video!\n- Watch the video to understand its SUCCESS FORMULA (structure, pacing, tone, character archetypes)\n- Do NOT describe what happens in the... [truncated]
SERIES_VIDEO_ANALYSIS_OVERRIDE = "\n⚠️ SERIES MODE ACTIVE — new EPISODE, same cast!\n- Describe every character, the world, and the visual style EXACTLY as seen — they are FIXED series assets and must be reproduced identically in the... [truncated]
CREATIVE_ASSET_OVERRIDE = '\n⚠️ CREATIVE MODE — INVENT NEW ASSETS:\n- Characters: SAME archetype/role as original (hero, sidekick, villain) but DIFFERENT species/appearance/name\n- Objects: SAME function but DIFFERENT style (o... [truncated]
CREATIVE_SCENE_OVERRIDE = '\n⚠️ CREATIVE MODE — WRITE NEW SCENES:\n- Use the SAME pacing pattern as original (if original: slow→fast→slow, yours: slow→fast→slow)\n- Use the SAME story structure (if original: intro→conflict→res... [truncated]

# --- Class: CharacterConsistencyError ---
class CharacterConsistencyError(Exception):
    """Raised when character image generation fails"""
    def __init__(self, errors: list, generated: int = 0, total: int = 0, policy_failed_characters=None):
        pass


# --- Class: CloneVideoError ---
class CloneVideoError(Exception):
    """Raised when video cloning fails"""
    pass


# --- Class: CloneSourceUploadLimitError ---
class CloneSourceUploadLimitError(CloneVideoError):
    """Terminal source-media policy error.

    This is intentionally distinct from a transient network/upload failure:
    callers must not retry it and must never fall back to base64 inline."""
    terminal_code = 'source_upload_limit_exceeded'

    def __init__(self, *, size_bytes: int, limit_bytes: int, provider_label: str, message: str = ''):
        pass


# --- Class: _YtDlpLogger ---
class _YtDlpLogger:
    """Custom logger cho yt-dlp — tránh lỗi 'write() argument must be str, not bytes' trên Windows/PyQt6."""
    def __init__(self):
        pass

    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        pass


# --- Class: YouTubeCloneService ---
class YouTubeCloneService:
    """Service để clone video YouTube thành script"""
    HARDCODED_KEYS = ['AIzaSyDI7E-ZKT3yr7Hvm7p2S5HnBAyTTP3FrfU', 'AIzaSyB-XNkw3EcW1Xv2r0c4Lo_Oppt0LkM6BQo', 'AIzaSyCDJ4iEqA0HSxm15SN-MMnmEZGh...
    YOUTUBE_API_KEYS = <property object at 0x00000264E6528310>
    youtube_session = <property object at 0x00000264E6529B20>
    ai_provider = <property object at 0x00000264E652A070>
    _SERIES_DNA_REQUIRED_FIELDS = ('series_structure_type', 'continuity_model', 'channel_promise', 'subject_domain', 'audience_level', 'episode_grammar', ...
    _REMIX_CONTRACT_REQUIRED_FIELDS = ('story_invariants', 'source_beat_functions', 'dialogue_intents', 'emotional_arc', 'primary_visible_axis', 'transformati...
    _CREATIVE_CONTRACT_REQUIRED_FIELDS = ('source_content_summary', 'audience_reward', 'hook_mechanism', 'format_grammar', 'pacing_curve', 'emotional_arc', 'enga...
    _MODE_CONTRACT_META = {'remix': ('remix_contract', ('story_invariants', 'source_beat_functions', 'dialogue_intents', 'emotional_arc', 'primary...
    _STYLE_LOOK_KEYS = ('global_style_override', 'summary', 'lighting_palette', 'dispatch_style_override', 'style_dispatch_override')
    _OUTPUT_TOKENS_PER_SCENE = 500

    def __init__(self, settings=None):
        pass

    def _init_cookies_dir(self) -> str:
        pass

    def get_cookie_file(self, platform: str, *, allow_generic_fallback: bool = True) -> Optional[str]:
        pass

    def _detect_platform(self, url: str) -> str:
        pass

    def _extract_domain_key(self, url: str) -> str:
        pass

    def _inject_cookies(self, ydl_opts: dict, url: str, *, force_cookie: bool = False) -> dict:
        pass

    @staticmethod
    def _needs_cookie_retry(error_text: str) -> bool:
        pass

    def _cookie_retry_options(self, ydl_opts: dict, url: str, error_text: str) -> Optional[dict]:
        pass

    def _playwright_cookies_to_netscape(self, cookies: list) -> str:
        pass

    def export_cookies_from_browser(self, platform: str, account_name: str = None) -> Optional[str]:
        pass

    def _refresh_platform_cookies(self, platform: str) -> Optional[str]:
        pass

    def _ensure_guest_cookies(self, platform: str, url: str = None) -> bool:
        pass

    def _maybe_refresh_cookies(self, platform: str, max_age_seconds: int = 1800) -> None:
        pass

    def get_platform_login_url(self, platform: str, url: str = None) -> str:
        pass

    def _get_dialogue_language_instruction(self, language_code: str) -> str:
        pass

    def _stash_duration(self, path: str, duration_seconds: int) -> None:
        pass

    def _stashed_duration(self, path: str) -> int:
        pass

    def _media_file_has_video_stream(self, path: str) -> bool:
        pass

    def _source_file_is_usable(self, source_url: str, path: str) -> bool:
        pass

    @staticmethod
    def _is_allowed_tiktok_media_url(url: str) -> bool:
        """Reject resolver payloads/redirects outside the expected media hosts."""
        pass

    def _resolve_tiktok_via_tikwm(self, url: str) -> Dict[str, Any]:
        pass

    def _resolve_tiktok_via_tikmate(self, url: str) -> Dict[str, Any]:
        pass

    def _get_tiktok_media_response(self, media_url: str):
        pass

    @staticmethod
    def _remove_temporary_media(path: str) -> None:
        pass

    def _download_tiktok_resolver_video(self, url: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def _download_tiktok_recovery(self, url: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def download_generic_video(self, url: str, progress_callback: Optional[Callable] = None, *, analysis_source: bool = False) -> Optional[str]:
        """Download video từ bất kỳ platform nào bằng yt-dlp (generic).
        Hỗ trợ: Facebook, Instagram, Twitter/X, Bilibili, và hầu hết các site."""
        pass

    def get_tiktok_metadata(self, tiktok_url: str, progress_callback: Optional[Callable] = None) -> Optional[Dict]:
        pass

    def _get_tiktok_metadata_playwright(self, tiktok_url: str, progress_callback: Optional[Callable] = None) -> Optional[Dict]:
        pass

    def _download_tiktok_playwright(self, url: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def upload_video_file(self, file_path: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def validate_local_source_for_upload(self, file_path: str, progress_callback: Optional[Callable] = None) -> None:
        pass

    @staticmethod
    def _is_upload_limit_error(error: Exception) -> bool:
        pass

    def _upload_video_file_once(self, file_path: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def get_channel_videos(self, channel_url: str, min_views: int = 0, max_results: int = 1000, video_type: str = 'all', progress_callback=None) -> list[typing.Dict]:
        pass

    def _get_video_info_youtube_api(self, url: str) -> Optional[Dict]:
        pass

    def _get_video_info_noembed(self, url: str) -> Optional[Dict]:
        pass

    def get_video_details(self, video_urls: list[str]) -> list[typing.Dict]:
        """Get metadata for video URLs. Platform-agnostic via yt-dlp ONLY.

        yt-dlp already supports YouTube, Facebook, TikTok, etc. — so there is a
        single extract path. The old YouTube-Data-API tier was removed: it 400'd on
        non-YouTube links (it tried to read a Facebook reel id as a YouTube id),
        wasting time and corrupting metadata. If yt-dlp can't fetch in time, the
        video is still allowed into the queue with minimal info (the real download
        happens later, also via yt-dlp)."""
        pass

    def _prepare_analysis_media_uploads(self, source_path: str, *, output_kind: str, progress_callback: Optional[Callable] = None):
        pass

    @staticmethod
    def _merge_segment_library(target: Any, incoming: Any) -> Any:
        pass

    def _analyze_segmented_media(self, segment_refs: list, *, clip_duration_seconds: int, output_kind: str, creative_mode: str, remix_instructions: str, progress_callback: Optional[Callable] = None, pipeline_trace_id: str = '', **analysis_kwargs) -> Dict:
        pass

    def clone_video(self, youtube_url: str, progress_callback: Optional[Callable] = None, temperature: float = 1.0, enable_character_consistency: bool = False, account_name: str = None, account_email: str = None, visual_style: str = None, remix_instructions: str = '', scene_interval: Union[int, str] = 2, dialogue_language: str = '', is_frame_slicing: bool = False, local_source_path: Optional[str] = None, target_market: str = 'global', char_mode: str = 'full_ai', selected_character_ids: list = None, selected_characters_data: dict = None, style_package: dict = None, clip_duration_seconds: int = 8, aspect_ratio: str = '16:9', multi_asset_info: dict = None, library_policy: dict = None, clone_job_id: str = None, charcore_event_callback: Optional[Callable] = None, enable_auto_style: bool = False, creative_mode: str = '', output_kind: str = 'video', image_pacing: str = 'auto', image_hold_seconds: float = 0.0, narration_wps: float = 0.0, image_motion_mode: str = 'off', narration_policy: str = 'auto', subtitle_profile: Optional[Dict[str, Any]] = None) -> Dict:
        pass

    def _analyze_and_clone_video(self, youtube_url: str, temperature: float = 1.0, duration_seconds: int = 0, remix_instructions: str = '', scene_interval: Union[int, str] = 2, dialogue_language: str = '', progress_callback: Optional[Callable] = None, enable_character_consistency: bool = False, target_market: str = 'global', char_mode: str = 'full_ai', selected_characters_data: dict = None, selected_character_ids: list = None, style_package: dict = None, clip_duration_seconds: int = 8, aspect_ratio: str = '16:9', multi_asset_info: dict = None, library_policy: dict = None, creative_mode: str = '', output_kind: str = 'video', image_pacing: str = 'auto', image_hold_seconds: float = 0.0, narration_wps: float = 0.0, image_motion_mode: str = 'off', narration_policy: str = 'auto', subtitle_profile: Optional[Dict[str, Any]] = None, pipeline_trace_id: str = '') -> Dict:
        pass

    def _build_pre_selected_chars_block(self, selected_characters_data: dict, selected_character_ids: list = None) -> str:
        pass

    def _library_categories_from_assets(self, multi_asset_info: Optional[Mapping[str, Any]]) -> list[str]:
        pass

    def _normalize_library_policy(self, library_policy: Optional[Mapping[str, Any]], *, char_mode: str, multi_asset_info: Optional[Mapping[str, Any]], selected_characters_data: Optional[Mapping[str, Any]]) -> dict[str, typing.Any]:
        pass

    def _library_assets_by_category(self, *, multi_asset_info: Optional[Mapping[str, Any]], selected_characters_data: Optional[Mapping[str, Any]], selected_character_ids: list | None) -> dict[str, list[dict[str, str]]]:
        pass

    def _library_lens_note(self, library_policy: Optional[Mapping[str, Any]], multi_asset_info: Optional[Mapping[str, Any]], selected_characters_data: Optional[Mapping[str, Any]]) -> str:
        pass

    def _mode_library_reconciliation(self, mode: str, library_policy: Optional[Mapping[str, Any]], multi_asset_info: Optional[Mapping[str, Any]]) -> str:
        pass

    def _build_library_policy_block(self, *, char_mode: str, selected_characters_data: Optional[Mapping[str, Any]], selected_character_ids: list | None, multi_asset_info: Optional[Mapping[str, Any]], library_policy: Optional[Mapping[str, Any]]) -> str:
        pass

    @staticmethod
    def _build_non_copy_gate(mode: str) -> str:
        pass

    @staticmethod
    def _default_mode_direction(mode: str) -> str:
        pass

    @classmethod
    def _mode_phase0_required_paths(cls, mode: str) -> list[str]:
        pass

    @classmethod
    def _mode_phase0_validation_spec(cls, mode: str) -> dict[str, typing.Any]:
        pass

    @staticmethod
    def _phase0_anchor_validation_rule() -> dict[str, typing.Any]:
        pass

    @classmethod
    def _series_phase0_required_paths(cls) -> list[str]:
        pass

    @staticmethod
    def _series_receipt_value_present(value: Any) -> bool:
        pass

    @staticmethod
    def _mode_uses_source_runtime(mode: str) -> bool:
        pass

    @staticmethod
    def _series_dna_missing_fields(result_data: Optional[Mapping[str, Any]]) -> list[str]:
        pass

    @classmethod
    def _mode_contract_payload(cls, result_data: Optional[Mapping[str, Any]], mode: str) -> Mapping[str, Any]:
        pass

    @classmethod
    def _mode_contract_missing_fields(cls, result_data: Optional[Mapping[str, Any]], mode: str) -> list[str]:
        pass

    def _build_task_block(self, mode: str, duration: int, scene_count: int, remix_instructions: str = '', clip_duration_seconds: int = 8) -> str:
        pass

    def _build_clone_output_example(self, *, duration: int, scene_count: int, clip_duration_seconds: int, natural_output_scope: bool = False) -> str:
        pass

    def _build_prompt(self, mode: str, duration: int, char_consistency: bool, dialogue_language: str, remix_instructions: str, target_market: str, char_mode: str = 'full_ai', selected_characters_data: dict = None, selected_character_ids: list = None, style_package: dict = None, clip_duration_seconds: int = 8, multi_asset_info: dict = None, library_policy: dict = None, narration_policy: str = 'auto') -> str:
        """Single assembly point for all clone prompts. Reads top-to-bottom."""
        pass

    @staticmethod
    def _image_hold_seconds(image_pacing: str = 'auto', duration_seconds: int = 0, auto_hint_seconds: float = 0.0) -> float:
        pass

    @classmethod
    def _target_image_scene_count(cls, duration_seconds: int, image_pacing: str = 'auto', auto_hint_seconds: float = 0.0) -> tuple[int, float]:
        pass

    def _build_video_native_blocks(self, *, mode: str, duration_seconds: int, clip_duration_seconds: int = 8, remix_instructions: str = '', narration_policy: str = 'auto') -> list[dict]:
        pass

    def _build_image_native_blocks(self, *, mode: str, duration_seconds: int, dialogue_language: str = '', image_pacing: str = 'auto', image_hold_seconds: float = 0.0, scenes_per_block: int = 24, remix_instructions: str = '', narration_wps: float = 0.0, style_package: dict = None, image_motion_mode: str = 'off') -> list[dict]:
        pass

    def _build_image_extract_prompt(self, mode: str, dialogue_language: str = '', target_market: str = 'global', style_package: dict = None, remix_instructions: str = '', source_duration_seconds: int = 0, image_pacing: str = 'auto', image_hold_seconds: float = 0.0, long_block_mode: bool = False, char_mode: str = 'full_ai', selected_characters_data: dict = None, selected_character_ids: list = None, multi_asset_info: dict = None, library_policy: dict = None, narration_wps: float = 0.0, image_motion_mode: str = 'off') -> str:
        pass

    def _validate_image_clone_result(self, result_data: Dict, *, source_duration_seconds: int, dialogue_language: str, remix_instructions: str = '', image_pacing: str = 'auto', image_hold_seconds: float = 0.0, narration_wps: float = 0.0, expected_scene_ids: Optional[list[str]] = None, mode: str = 'copy') -> None:
        pass

    @staticmethod
    def _validate_image_library_intent(result_data: Dict[str, Any], intent: Optional[Mapping[str, Any]]) -> None:
        """Hard gate selected assets into at least one authored script unit.

        The response guard protects the entity library surface. This gate proves
        the LLM actually authored the script around selected assets instead of
        returning them unused in entity_library as decoration."""
        pass

    @staticmethod
    def _effective_authoring_temperature(mode: str, temperature: Any) -> float:
        pass

    def _call_ai_for_one_step(self, youtube_url: str, temperature: float, duration_seconds: int, remix_instructions: str, scene_interval: Union[int, str], dialogue_language: str = '', progress_callback: Optional[Callable] = None, enable_character_consistency: bool = False, target_market: str = 'global', char_mode: str = 'full_ai', selected_characters_data: dict = None, selected_character_ids: list = None, style_package: dict = None, clip_duration_seconds: int = 8, aspect_ratio: str = '16:9', multi_asset_info: dict = None, library_policy: dict = None, creative_mode: str = '', output_kind: str = 'video', image_pacing: str = 'auto', image_hold_seconds: float = 0.0, narration_wps: float = 0.0, image_motion_mode: str = 'off', narration_policy: str = 'auto', subtitle_profile: Optional[Dict[str, Any]] = None, pipeline_trace_id: str = '') -> Dict:
        """All modes share one media+prompt authoring path. COPY locks the source
        timeline; REMIX/CREATIVE/SERIES differ only by mode task/gate prompts
        (_build_non_copy_gate, _build_task_block, CREATIVE/SERIES overrides).

        output_kind=="image" returns atomic narration/content units; the completed
        one-take WAV + verified SRT later owns image rhythm and final prompts through
        the shared Audio-to-Video analyzer. VIDEO authors contiguous fixed-duration
        output clips directly, with no post-TTS scene planner."""
        pass

    def _get_max_scene_end(self, scenes_dict: Dict) -> int:
        pass

    def download_youtube_video(self, url: str, progress_callback: Optional[Callable] = None) -> Optional[str]:
        pass

    def _prepare_slicing_assets(self, url: str, progress_callback: Optional[Callable] = None) -> Tuple[List[str], str]:
        pass

    def process_frame_slicing_clone(self, url: str, progress_callback: Optional[Callable] = None, analysis_result: Dict = None, precomputed_frames: List[str] = None, precomputed_video_path: str = None) -> Dict:
        pass

    def _apply_character_consistency(self, result_data: Dict, progress_callback: Optional[Callable], visual_style: str = None, clone_job_id: str = None, aspect_ratio: str = '16:9', multi_asset_info: Dict = None, char_mode: str = 'full_ai') -> Dict:
        pass

    def _has_tail_gap(self, scenes_dict: Dict, duration_seconds: int, max_tail_gap: int = 5) -> bool:
        pass

    def _validate_scene_ids_dict(self, data: Dict, scene_interval: int = 8) -> bool:
        pass

    def _convert_scenes_dict_to_array(self, data: Dict) -> Dict:
        """Convert fixed-duration scenes dictionary to final array format.

        Input: {"scenes": {"0-4": "...", "4-8": "..."}}
        Output: {"scenes": [{"scene_id": "0-4", "visual": "..."}, ...]}

        The AI already returns fixed-duration scenes. This only converts the
        dictionary to an array without legacy flexible-scene merging."""
        pass

    def _clean_youtube_url(self, url: str) -> str:
        pass

    def _stamp_auto_style(self, result_data: Dict, auto_style_pkg: Optional[Dict]) -> None:
        pass

    @staticmethod
    def _is_bare_style_id(value: Any) -> bool:
        pass

    @classmethod
    def _style_text_from_mapping(cls, mapping: Any, _depth: int = 0, _seen: Any = None) -> str:
        pass

    @classmethod
    def _resolve_chargen_visual_style(cls, *, visual_style: Any = None, style_package: Any = None, result_data: Optional[Dict] = None, asset_library: Any = None) -> str:
        pass

    @classmethod
    def _find_look_object(cls, obj, _depth: int = 0) -> Optional[Dict]:
        """Tìm dict MANG LOOK trong một payload có thể bị bọc.

        Model được bảo "Return ONLY this JSON object" nhưng vẫn hay bọc thêm một lớp
        (`{"framework_definition": {...}}`, `{"style": {...}}`, `{"result": {...}}`) —
        khi đó check key ở TẦNG TRÊN CÙNG luôn trượt và cả response bị vứt. Lặn xuống
        vài tầng và nhận dict đầu tiên có key mang look."""
        pass

    def suggest_clone_angles(self, youtube_url: str, count: int = 5, is_uploaded_file: bool = False, progress_callback: Optional[Callable] = None) -> list:
        pass

    def _cut_video_head(self, src: str, seconds: int = 60) -> str:
        pass

    def _remember_source_output_classification(self, source_url: str, result: str, payload: Optional[Dict[str, Any]] = None) -> None:
        pass

    def source_output_classification_details(self, source_url: str) -> Dict[str, Any]:
        pass

    def classify_source_output(self, youtube_url: str, *, is_uploaded_file: bool = False, local_source_path: Optional[str] = None, progress_callback: Optional[Callable] = None) -> str:
        """AUTO mode — choose the RECREATION pipeline, not a raw pixel-motion label.

        IMAGE means narration-led visuals that remain faithful as timed still-image
        beats (including whiteboard/doodle explainers and limited motion graphics).
        VIDEO means temporal action/performance/camera movement is essential and still
        frames would lose meaning. Returns ``"image"`` | ``"video"``.

        1 call RẺ (mirror suggest_clone_angles, duration_seconds=0): nếu có file local thì cắt
        ~1 phút đầu gửi cho AI (video dài khỏi đọc trọn); không có local → xem thẳng nguồn.
        Lỗi/parse trượt → "video" (AN TOÀN — giữ hành vi cũ, không bịa ra ảnh)."""
        pass

    def cached_source_local_path(self, source_url: str) -> str:
        pass

    def _parse_style_framework_json(self, text: str) -> Optional[Dict]:
        pass

    def _extract_style_frames(self, path: str, count: int = 6, max_width: int = 768) -> list:
        pass

    def _extract_style_framework(self, youtube_url: str, temperature: float = 0.6, is_uploaded_file: bool = False, source_title: str = '', local_source_path: str = None) -> Optional[Dict]:
        pass

    def _call_gemini_api(self, prompt: str, youtube_url: str, temperature: float = 1.0, max_output_tokens: int = 65536, duration_seconds: int = 0, preferred_api_key: str = None, is_uploaded_file: bool = False, enable_character_consistency: bool = False, completion_spec: dict = None, clip_duration_seconds: int = 8, blocks_override: Optional[list[dict]] = None, progress_callback: Optional[Callable] = None, feature: str = 'clone_video') -> str:
        """Call AI API via smart_generate_with_media().

        One logical job may be one request (short source) or a provider-managed
        Phase-0 + manifest block sequence (long source)."""
        pass

    def _parse_json_object(self, response: str, *, required_keys: tuple[str, ...], phase: str) -> Dict:
        """Strictly parse one phase-specific JSON object without fabricating data.

        Native mode prompts intentionally expose
        different top-level keys.  They must not pass through the legacy final
        Clone parser, whose valid contract requires both entity_library + scenes."""
        pass

    def _parse_response(self, response: str) -> Dict:
        pass

    def _clean_json_response(self, response: str) -> str:
        pass

    def _validate_structure(self, data: Dict) -> bool:
        pass

    def _is_valid_video_url(self, url: str) -> bool:
        pass

    def check_video_duration(self, youtube_url: str) -> Tuple[bool, Optional[Dict]]:
        pass

    def _extract_video_id(self, url: str) -> Optional[str]:
        pass

    def _parse_duration_iso(self, duration: str) -> int:
        pass

    def _get_uploaded_file_duration(self, file_uri: str) -> int:
        pass

    def _cached_duration_by_uri(self, file_uri: str) -> int:
        pass

    def estimate_prompt_tokens(self, duration_seconds: int = 60, clip_duration_seconds: int = 8, target_market: str = 'global', mode: str = 'normal') -> int:
        pass

    def estimate_output_tokens(self, duration_seconds: int = 60, clip_duration_seconds: int = 8) -> int:
        pass

    def _get_token_count(self, youtube_url: str) -> int:
        pass


# --- Top-Level Functions ---
def _is_valid_http_url(value) -> bool:
    pass

def _build_narrator_voice_catalog_block() -> str:
    pass

def _adapt_clone_duration_text(text: str, clip_duration_seconds: int) -> str:
    pass

def _prompt_text(value: Any) -> str:
    pass

def _dedupe_ordered(values: list[str]) -> list[str]:
    pass

def _library_category(value: Any) -> str:
    pass

def _library_mode(value: Any, char_mode: Any = '') -> str:
    pass

def _join_with_or(values: list[str]) -> str:
    pass

def _ensure_clone_entity_libraries(data: Dict) -> Dict:
    pass

def get_youtube_clone_service(settings=None) -> services.tabs.clone_video.youtube_clone_service.YouTubeCloneService:
    pass
